/**
 * Diff the browser's landmark vector builder against vectors generated by the
 * Python reference (isl-recognition/scripts/dump_expected_vectors.py).
 *
 * This is the check that matters most for correctness. If the JS normalization
 * drifts from `normalize_single_hand` even slightly, every prediction is wrong
 * and nothing else in the stack will reveal it, because the backend happily
 * scores whatever 126 floats it receives.
 *
 * The fixtures cover both handedness-inversion settings, but the browser ships
 * one fixed setting. Cases matching the shipped setting are compared
 * numerically; the other direction is asserted to differ, which is what proves
 * the inversion is actually doing something rather than silently passing.
 *
 * Run: npm run check:vectors
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import {
  FRAME_BYTES,
  INVERT_HANDEDNESS,
  TOTAL_FEATURES,
  buildVector,
  isEmptyVector,
} from '../src/services/landmarkVector.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(
  here,
  '../src/services/__fixtures__/expectedVectors.json',
);

const cases = JSON.parse(readFileSync(fixturePath, 'utf8'));

/**
 * Tolerance sits just above float32 storage error. The Python side computes in
 * float64 and the JS returns float32, so the two can never match exactly;
 * anything larger means a real logic difference, not rounding.
 */
const TOLERANCE = 1e-6;

let failures = 0;
let compared = 0;
let worst = 0;
let inversionChecks = 0;

const active = cases.filter((c) => c.invert === INVERT_HANDEDNESS);
const inactive = cases.filter((c) => c.invert !== INVERT_HANDEDNESS);

for (const testCase of active) {
  const actual = buildVector(testCase.hands);

  if (actual.length !== TOTAL_FEATURES) {
    console.error(
      `FAIL ${testCase.name}: length ${actual.length} != ${TOTAL_FEATURES}`,
    );
    failures += 1;
    continue;
  }

  if (actual.byteLength !== FRAME_BYTES) {
    console.error(
      `FAIL ${testCase.name}: ${actual.byteLength} bytes != ${FRAME_BYTES}`,
    );
    failures += 1;
    continue;
  }

  const expected = testCase.vector;
  let caseWorst = 0;
  let worstIndex = 0;
  for (let i = 0; i < expected.length; i += 1) {
    const delta = Math.abs(actual[i] - expected[i]);
    if (delta > caseWorst) {
      caseWorst = delta;
      worstIndex = i;
    }
  }
  worst = Math.max(worst, caseWorst);
  compared += 1;

  if (caseWorst > TOLERANCE) {
    failures += 1;
    console.error(
      `FAIL ${testCase.name}: max |delta| ${caseWorst.toExponential(3)} at ` +
      `index ${worstIndex} (js ${actual[worstIndex]} vs py ${expected[worstIndex]})`,
    );
  }
}

// For the configuration the browser does not ship, confirm the vectors really
// differ. Identical output in both directions would mean the handedness label
// is being ignored, which would silently break every prediction.
for (const testCase of inactive) {
  if (testCase.hands.length === 0) continue;
  const actual = buildVector(testCase.hands);
  const expected = testCase.vector;
  let differs = false;
  for (let i = 0; i < expected.length; i += 1) {
    if (Math.abs(actual[i] - expected[i]) > TOLERANCE) {
      differs = true;
      break;
    }
  }
  if (!differs) {
    failures += 1;
    console.error(
      `FAIL ${testCase.name}: vector matches the non-inverted reference, so ` +
      'the handedness label is not affecting slot assignment',
    );
  } else {
    inversionChecks += 1;
  }
}

// isEmptyVector must agree with an all-zero reference vector.
const emptyCase = cases.find((c) => c.name === 'empty');
if (emptyCase && !isEmptyVector(buildVector(emptyCase.hands))) {
  console.error('FAIL isEmptyVector: returned false for an empty frame');
  failures += 1;
}

if (failures > 0) {
  console.error(
    `\n${failures} failure(s): ${compared} case(s) compared, ` +
    `${inversionChecks} inversion check(s).`,
  );
  process.exit(1);
}

console.log(
  `Landmark vectors match the Python reference.\n` +
  `  ${compared} case(s) compared at invert=${INVERT_HANDEDNESS} ` +
  `(max |delta| ${worst.toExponential(2)}, tolerance ${TOLERANCE})\n` +
  `  ${inversionChecks} case(s) confirm the opposite setting differs\n` +
  `  frame size ${FRAME_BYTES} bytes, ${TOTAL_FEATURES} features`,
);
